repos:
  - repo: local
    hooks:
      - id: make-check
        name: make check (full CI validation)
        entry: make check
        language: system
        pass_filenames: false
        types: [python]
